image: Visual Studio 2017

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: Rename-Item -NewName Docker.old "C:\Program Files\Docker"
  - cmd: choco install docker-for-windows --pre
  - cmd: choco install docker-compose
  #- ps: Rename-Item -NewName Docker.new "C:\Program Files\Docker"
  #- ps: New-Item -Path "C:\Program Files\Docker" -ItemType SymbolicLink -Value "C:\Program Files\Docker\Docker.new"
  - cmd: refreshenv
  - cmd: path C:\Program Files\Docker\Docker;C:\Program Files\Docker\Docker\resources\bin;%PATH%
  - cmd: where docker
  - cmd: where docker-compose
  - cmd: where DockerCli
  - cmd: docker version
  - cmd: docker-compose version
  - cmd: DockerCli -Version
  - cmd: DockerCli -SwitchDaemon
  - ps: .\scripts\ci\StrongNameKey.ps1
  - ps: .\scripts\ci\CodeSigningCertificate.ps1
  - ps: nuget restore -Source $env:NUGET_SOURCE_URL

build_script:
  - ps: .\scripts\ci\Build.ps1

deploy_script:
  - ps: if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_REPO_BRANCH -eq "releases") { .\scripts\ci\DeployDocker.ps1 }
