image: Visual Studio 2017

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - cmd: choco install docker-for-windows --pre
  - cmd: choco install docker-compose
  - cmd: "C:\\Program Files\\Docker\\Docker\\DockerCli.exe" -SwitchDaemon
  - ps: .\scripts\ci\StrongNameKey.ps1
  - ps: .\scripts\ci\CodeSigningCertificate.ps1
  - ps: nuget restore -Source $env:NUGET_SOURCE_URL

build_script:
  - ps: .\scripts\ci\Build.ps1

deploy_script:
  - ps: if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_REPO_BRANCH -eq "releases") { .\scripts\ci\DeployDocker.ps1 }
